# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1f095ff2-367a-4e1e-b8f4-deba6ceabfdf";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7554-C1CF";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Graphics drivers for Intel Arrow Lake-P
  hardware.graphics = {
    enable = true;
    enable32Bit = true;  # Enable 32-bit support for games/compatibility
    extraPackages = with pkgs; [
      intel-media-driver  # VAAPI driver for newer Intel GPUs
      intel-compute-runtime  # OpenCL support
      libvdpau-va-gl
      libva-vdpau-driver
    ];
  };

  # Enable Intel graphics firmware
  hardware.enableRedistributableFirmware = true;
}
