# SOPS configuration for secret encryption
# https://github.com/Mic92/sops-nix

keys:
  # Nauvoo (Linux workstation)
  - &nauvoo age1wjqs46cr6jh6zv935x45j5atlam25up5vugkjdmpsy0nz0gz9gvqgnqc5c
  # MacBook (Apple Silicon)
  # Derived from SSH host key: sudo ssh-to-age < /etc/ssh/ssh_host_ed25519_key.pub
  - &macbook age1f7qtq4w5tqzn4g42cp77wux2ce346e6y390vu82r4g99csehmsjs0y55n6
  # This lets you decrypt all secrets on any machine
  - &admin age1wjqs46cr6jh6zv935x45j5atlam25up5vugkjdmpsy0nz0gz9gvqgnqc5c

  - &razorback age1a50mjzu5wks736rzhwn8wcn00v83agxuvh6785nfuh2uv3mavunq6hu06r

  - &kayda age150p2u8vqrqg7jmgxqqzy308elrup08p0mln3lpvr8wyj6yswhguqxsz8eq

creation_rules:
  # Host-specific secrets (each host can only decrypt its own)
  - path_regex: hosts/nauvoo/secrets\.yaml$
    key_groups:
      - age:
          - *nauvoo
          - *admin

  - path_regex: hosts/razorback/secrets\.yaml$
    key_groups:
      - age:
          - *razorback
          - *admin

  - path_regex: hosts/macbook/secrets\.yaml$
    key_groups:
      - age:
          - *macbook
          - *admin

  - path_regex: home/users/dinesh\.reddy/secrets\.yaml$
    key_groups:
      - age:
          - *macbook
          - *admin

  - path_regex: hosts/kayda/secrets\.yaml$
    key_groups:
      - age:
          - *kayda
          - *admin

  # Shared secrets (all hosts can decrypt)
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *nauvoo
          - *macbook
          - *razorback
          - *kayda
          - *admin
