name: Build Configurations

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build-nixos:
    runs-on: ubuntu-latest
    strategy:
      # This creates two parallel jobs: one for nauvoo, one for razorback
      matrix:
        host: [nauvoo, razorback]
      fail-fast: false # Keep building one even if the other fails

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            sandbox = false

      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: jagadam97
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pushFilter: '(^cache\.nixos\.org-|^nix-community\.cachix\.org-|^jagadam97\.cachix\.org-)'

      - name: Build and cache NixOS config
        # The ${{ matrix.host }} syntax dynamically inserts the machine name
        continue-on-error: true
        run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel --keep-going
