name: Build NixOS Configurations

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            sandbox = false

      - name: Setup Cachix
        uses: cachix/cachix-action@v14
        with:
          name: jagadam97
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          pushFilter: '(^cache\.nixos\.org-|^nix-community\.cachix\.org-)'

      - name: Check NixOS config (dry-build)
        run: nix build .#nixosConfigurations.nauvoo.config.system.build.toplevel --dry-run --impure --refresh

      # Add more hosts here as you create them:
      # - name: Check laptop configuration
      #   run: nix eval .#nixosConfigurations.laptop.config.system.build.toplevel --impure